registry.saas.hand-china.com/tools/mysql:5.6

ADD ./docker/mysql  /
#RUN mysql -uroot -padmin -e "create database sakila;use sakila;source sakila-schema.sql;source sakila-data.sql;grant all privileges on *.* to 'root'@'%';flush privileges;"


